### ISSUE TITLE
Error when run extract.py

### ISSUE THREAD

**Issue by tangbing9922** [ArrowLuo/VideoFeatureExtractor#1]
thank you for your work！
when i run the extract.py in command
`python extract.py --csv=./input.csv --type=s3dg --batch_size=64 --num_decoding_thread=1
D:\Github\VideoFeatureExtractor
Loading S3DG ...
Weights from pretrained model not used in S3D:
   text_module.word_embd.weight
   text_module.fc1.weight
   text_module.fc1.bias
   text_module.fc2.weight
   text_module.fc2.bias
loaded
D:\Github\VideoFeatureExtractor
Decoding video: D:/Github/VideoFeatureExtractor/data/1.mp4
ffprobe failed at: D:/Github/VideoFeatureExtractor/data/1.mp4
Video D:/Github/VideoFeatureExtractor/data/1.mp4 already processed.Decoding video: D:/Github/VideoFeatureExtractor/data/2.mp4

ffprobe failed at: D:/Github/VideoFeatureExtractor/data/2.mp4
Video D:/Github/VideoFeatureExtractor/data/2.mp4 already processed.`
Could you check with it?

**Comment by ArrowLuo** [comment]
@tangbing9922 so sorry missed your information. I think this question is caused by your FFmpeg installation. Or, this video file is not right?
